const DEFAULT_ITEMS = [
  {
    item_type_cn: "定制大堂扶手椅",
    item_type_en: "Custom Lobby Armchair",
    quantity: 40,
    material_cn: "海军蓝亚麻 (待确认)",
    material_en: "Navy Classic Linen (to confirm)",
    original_unit_price: 210,
    unit_price: 210,
    notes_cn: "由 Intake Worker 根据客户资料自动生成，待 Cho 技术复核。",
    notes_en: "Generated by Intake Worker from client materials; pending Cho technical review."
  }
];

export async function parseIntakeBrief({ job, file }) {
  if (process.env.DEEPSEEK_API_KEY) {
    try {
      return await parseWithDeepSeek({ job, file });
    } catch (err) {
      console.warn("AI parse failed, falling back to deterministic parser:", err.message);
    }
  }

  return parseDeterministically({ job, file });
}

async function parseWithDeepSeek({ job, file }) {
  const schema = intakeResultSchema();
  const systemPrompt = [
    "You are Crafton AI Intake Agent for bespoke furniture manufacturing.",
    "Return strict JSON only. Extract a project brief, destination, items, and missing questions.",
    "Use conservative assumptions. Do not invent production-critical dimensions.",
    "The response must be a JSON object that matches this JSON schema:",
    JSON.stringify(schema)
  ].join("\n");

  const userPrompt = [
    "Parse this intake brief into JSON.",
    "",
    `Project name: ${job.project_name || ""}`,
    `Destination: ${job.destination || ""}`,
    `Quantity text: ${job.quantity_text || ""}`,
    `Brief text: ${job.brief_text || ""}`,
    `Uploaded file name: ${file?.original_name || "none"}`,
    `Uploaded file mime: ${file?.mime_type || "unknown"}`
  ].join("\n");

  const baseUrl = (process.env.DEEPSEEK_BASE_URL || "https://api.deepseek.com").replace(/\/+$/, "");
  const response = await fetch(`${baseUrl}/chat/completions`, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${process.env.DEEPSEEK_API_KEY}`,
      "Content-Type": "application/json"
    },
    body: JSON.stringify({
      model: process.env.DEEPSEEK_MODEL || "deepseek-v4-flash",
      messages: [
        { role: "system", content: systemPrompt },
        { role: "user", content: userPrompt }
      ],
      response_format: { type: "json_object" },
      stream: false
    })
  });

  if (!response.ok) {
    const body = await response.text();
    throw new Error(`DeepSeek parse request failed: ${response.status} ${body}`);
  }

  const data = await response.json();
  const text = data.choices?.[0]?.message?.content;
  if (!text) throw new Error("DeepSeek response did not include output text.");

  return normalizeResult(JSON.parse(stripJsonFence(text)), job);
}

function parseDeterministically({ job, file }) {
  const qty = extractFirstQuantity(job.quantity_text) || 40;
  const projectName = job.project_name || `CRAFT-${new Date().getFullYear()}-INTAKE`;
  const destination = job.destination || "United Kingdom Warehouse";

  const items = [
    {
      ...DEFAULT_ITEMS[0],
      quantity: qty
    }
  ];

  const briefParts = [job.brief_text, job.quantity_text, file?.original_name].filter(Boolean);

  return normalizeResult(
    {
      project: {
        name: projectName,
        client_name: "Portal Intake Client",
        destination
      },
      items,
      questions: [
        "Please confirm exact dimensions for each furniture type.",
        "Please confirm final fabric code and fire-retardancy requirement.",
        "Please confirm target delivery date and warehouse receiving window."
      ],
      summary_cn: `已接收 ${projectName} 的客户资料，目的地 ${destination}，初步识别 ${qty} 件定制家具。`,
      summary_en: `Received client materials for ${projectName}, destination ${destination}; initially detected ${qty} bespoke furniture items.`,
      source_notes: briefParts.join(" | ")
    },
    job
  );
}

function normalizeResult(result, job) {
  const total = (result.items || DEFAULT_ITEMS).reduce((sum, item) => {
    return sum + Number(item.quantity || 0) * Number(item.unit_price || 0);
  }, 0);

  return {
    project: {
      name: result.project?.name || job.project_name || `CRAFT-${Date.now()}`,
      client_name: result.project?.client_name || "Portal Intake Client",
      destination: result.project?.destination || job.destination || "United Kingdom Warehouse"
    },
    items: result.items && result.items.length > 0 ? result.items : DEFAULT_ITEMS,
    payments: [
      {
        milestone_cn: "50% 首期定金",
        milestone_en: "50% Deposit",
        amount: roundMoney(total * 0.5),
        status: "Pending",
        payment_date: "Pending"
      },
      {
        milestone_cn: "40% 出货中款",
        milestone_en: "40% Shipping Release",
        amount: roundMoney(total * 0.4),
        status: "Pending",
        payment_date: "Pending"
      },
      {
        milestone_cn: "10% 交付尾款",
        milestone_en: "10% Handover Balance",
        amount: roundMoney(total * 0.1),
        status: "Pending",
        payment_date: "Pending"
      }
    ],
    questions: result.questions || [],
    summary_cn: result.summary_cn || "Intake Worker 已完成初步解析，等待 Cho 复核。",
    summary_en: result.summary_en || "Intake Worker completed first-pass parsing; pending Cho review.",
    source_notes: result.source_notes || job.brief_text || ""
  };
}

function extractFirstQuantity(text = "") {
  const match = String(text).match(/\d+/);
  return match ? Number(match[0]) : null;
}

function roundMoney(value) {
  return Math.round(Number(value || 0) * 100) / 100;
}

function stripJsonFence(text) {
  return String(text)
    .trim()
    .replace(/^```(?:json)?\s*/i, "")
    .replace(/\s*```$/i, "")
    .trim();
}

function intakeResultSchema() {
  return {
    type: "object",
    additionalProperties: false,
    required: ["project", "items", "questions", "summary_cn", "summary_en", "source_notes"],
    properties: {
      project: {
        type: "object",
        additionalProperties: false,
        required: ["name", "client_name", "destination"],
        properties: {
          name: { type: "string" },
          client_name: { type: "string" },
          destination: { type: "string" }
        }
      },
      items: {
        type: "array",
        items: {
          type: "object",
          additionalProperties: false,
          required: [
            "item_type_cn",
            "item_type_en",
            "quantity",
            "material_cn",
            "material_en",
            "original_unit_price",
            "unit_price",
            "notes_cn",
            "notes_en"
          ],
          properties: {
            item_type_cn: { type: "string" },
            item_type_en: { type: "string" },
            quantity: { type: "integer" },
            material_cn: { type: "string" },
            material_en: { type: "string" },
            original_unit_price: { type: "number" },
            unit_price: { type: "number" },
            notes_cn: { type: "string" },
            notes_en: { type: "string" }
          }
        }
      },
      questions: { type: "array", items: { type: "string" } },
      summary_cn: { type: "string" },
      summary_en: { type: "string" },
      source_notes: { type: "string" }
    }
  };
}
